---
image:
  - Visual Studio 2022

platform: x64

branches:
  only:
    - master
    - appveyor

skip_tags: true

install:
  - python --version
  - pip install yamllint

build_script:
  - ps: yamllint @(Get-ChildItem *.yml -Recurse)
